version: 0.2

phases:
  install:
    commands:
      - echo "Updating package lists on Amazon Linux..."
      - yum update -y
      - echo "Installing Nginx on Amazon Linux..."
      - amazon-linux-extras install nginx1.12 -y
      - echo "Starting Nginx service..."
      - service nginx start
      - echo "Enabling Nginx to start on boot..."
      - chkconfig nginx on

  build:
    commands:
      - echo "Build process started on `date`"
      - echo "Copying index.html to the web root..."
      - cp index.html /usr/share/nginx/html/index.html
      - echo "Build completed successfully."

  post_build:
    commands:
      - echo "Post-build steps..."
      - echo "Displaying Public IP or Hostname..."
      - curl -s http://169.254.169.254/latest/meta-data/public-ipv4 || hostname
      - echo "Build and deployment process finished."

artifacts:
  files:
    - /usr/share/nginx/html/index.html



